# Generated by Django 2.2 on 2019-05-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, unique=True)),
                ('description', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('minQuan', models.IntegerField(default=0)),
                ('maxQuan', models.IntegerField(default=9223372036854775807)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, unique=True)),
                ('description', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_quantity', models.IntegerField(default=9223372036854775807)),
                ('min_quantity_retail', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='prod_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='prod_dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.discount')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.products')),
            ],
        ),
    ]
