# Generated by Django 2.2.1 on 2019-05-11 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pantry & Dry Goods', 'Pantry & Dry Goods'), ('Bath & Facial Tissue', 'Bath & Facial Tissue'), ('Canned Goods', 'Canned Goods'), ('Cleaning Products', 'Cleaning Products'), ('Coffee & Sweeteners', 'Coffee & Sweeteners'), ('Emergency Kits & Supplies', 'Emergency Kits & Supplies'), ('Breakroom Serving Supplies', 'Breakroom Serving Supplies'), ('Gourmet Foods', 'Gourmet Foods'), ('Paper Towels', 'Paper Towels'), ('Snacks', 'Snacks'), ('Water & Beverages', 'Water & Beverages')], default='Pantry & Dry Goods', max_length=50)),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custFName', models.CharField(max_length=50, null=True)),
                ('custLName', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('custAddress', models.CharField(max_length=80)),
                ('custCity', models.CharField(max_length=50)),
                ('custState', models.CharField(max_length=2)),
                ('custZip', models.IntegerField()),
                ('custPhone', models.CharField(max_length=20)),
                ('businessName', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('minQuan', models.IntegerField(default=0)),
                ('maxQuan', models.IntegerField(default=9223372036854775807)),
                ('disShipping', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('shippedDate', models.DateField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNumber', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Discount')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShipMethName', models.CharField(max_length=80, unique=True)),
                ('ShipMethDesc', models.TextField(max_length=250)),
                ('ShipMethPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipAddFname', models.CharField(max_length=50, null=True)),
                ('shipAddLname', models.CharField(max_length=50, null=True)),
                ('businessName', models.CharField(max_length=50, null=True)),
                ('shipAddAddress', models.CharField(max_length=80)),
                ('shipAddCity', models.CharField(max_length=50)),
                ('shipAddState', models.CharField(max_length=2)),
                ('shipAddZip', models.IntegerField()),
                ('shipAddPhone', models.CharField(max_length=20)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, unique=True)),
                ('description', models.CharField(default='', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_quantity', models.IntegerField(default=9223372036854775807)),
                ('min_quantity_retail', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Category')),
                ('discount', models.ManyToManyField(through='wholesale.Prod_dis', to='wholesale.Discount')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Products')),
            ],
        ),
        migrations.AddField(
            model_name='prod_dis',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Products'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='wholesale.Prod_order', to='wholesale.Products'),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.ShippingAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.ShippingMethod'),
        ),
        migrations.AddField(
            model_name='customers',
            name='PaymentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Payment'),
        ),
    ]
