# Generated by Django 2.1.8 on 2019-06-03 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busName', models.CharField(max_length=30)),
                ('busAddress', models.CharField(max_length=30)),
                ('busZip', models.CharField(max_length=30)),
                ('busCity', models.CharField(max_length=30)),
                ('busState', models.CharField(max_length=2)),
                ('busEmail', models.EmailField(max_length=30)),
                ('busPhone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodQuantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pantry & Dry Goods', 'Pantry & Dry Goods'), ('Bath & Facial Tissue', 'Bath & Facial Tissue'), ('Canned Goods', 'Canned Goods'), ('Cleaning Products', 'Cleaning Products'), ('Coffee & Sweeteners', 'Coffee & Sweeteners'), ('Emergency Kits & Supplies', 'Emergency Kits & Supplies'), ('Breakroom Serving Supplies', 'Breakroom Serving Supplies'), ('Gourmet Foods', 'Gourmet Foods'), ('Paper Towels', 'Paper Towels'), ('Snacks', 'Snacks'), ('Water & Beverages', 'Water & Beverages')], default='Pantry & Dry Goods', max_length=50)),
                ('image', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custFName', models.CharField(max_length=50, null=True)),
                ('custLName', models.CharField(max_length=50, null=True)),
                ('custAddress', models.CharField(max_length=80)),
                ('custCity', models.CharField(max_length=50)),
                ('custState', models.CharField(max_length=2)),
                ('custZip', models.CharField(max_length=20)),
                ('custPhone', models.CharField(max_length=20)),
                ('businessName', models.CharField(max_length=50, null=True)),
                ('custLevel', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=0.0)),
                ('minQuan', models.IntegerField(default=0)),
                ('maxQuan', models.IntegerField(default=9223372036854775807)),
                ('test', models.IntegerField(default=9223372036854775807)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('shippedDate', models.DateField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNumber', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, unique=True)),
                ('description', models.CharField(default='', max_length=250)),
                ('image', models.URLField(null=True)),
                ('price', models.FloatField(default=0.0)),
                ('max_quantity', models.IntegerField(default=9223372036854775807)),
                ('min_quantity_retail', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipAddFname', models.CharField(max_length=50, null=True)),
                ('shipAddLname', models.CharField(max_length=50, null=True)),
                ('businessName', models.CharField(max_length=50, null=True)),
                ('shipAddAddress', models.CharField(max_length=80)),
                ('shipAddCity', models.CharField(max_length=50)),
                ('shipAddState', models.CharField(max_length=2)),
                ('shipAddZip', models.CharField(max_length=20)),
                ('shipAddPhone', models.CharField(max_length=20)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShipMethName', models.CharField(max_length=80, unique=True)),
                ('ShipMethDesc', models.TextField(max_length=250)),
                ('ShipMethPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.ShippingAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.ShippingMethod'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Products'),
        ),
        migrations.AddField(
            model_name='customers',
            name='PaymentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wholesale.Payment'),
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Customers'),
        ),
        migrations.AddField(
            model_name='cart',
            name='prodName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Products'),
        ),
    ]
