# Generated by Django 2.1.8 on 2019-06-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='test',
        ),
    ]
