# Generated by Django 2.2.1 on 2019-05-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='username',
        ),
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
