# Generated by Django 2.1.8 on 2019-06-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_remove_discount_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='maxQuan',
            field=models.IntegerField(default=2147483647),
        ),
        migrations.AlterField(
            model_name='products',
            name='max_quantity',
            field=models.IntegerField(default=2147483647),
        ),
    ]
