# Generated by Django 2.2.1 on 2019-05-12 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_auto_20190511_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='PaymentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wholesale.Payment'),
        ),
    ]
