# Generated by Django 2.2.1 on 2019-05-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0004_auto_20190512_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='custZip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipAddZip',
            field=models.CharField(max_length=20),
        ),
    ]
