# Generated by Django 2.1.8 on 2019-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0004_auto_20190605_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='maxQuan',
            field=models.IntegerField(default=2147483647),
        ),
        migrations.AlterField(
            model_name='products',
            name='max_quantity',
            field=models.IntegerField(default=2147483647),
        ),
    ]
