# Generated by Django 2.2.1 on 2019-05-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0005_auto_20190513_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busName', models.CharField(max_length=30)),
                ('busAddress', models.CharField(max_length=30)),
                ('busZip', models.CharField(max_length=30)),
                ('busCity', models.CharField(max_length=30)),
                ('busState', models.CharField(max_length=2)),
                ('busEmail', models.EmailField(max_length=30)),
                ('busPhone', models.CharField(max_length=30)),
            ],
        ),
    ]
