# Generated by Django 2.2 on 2019-05-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0006_auto_20190513_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='disShipping',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
