# Generated by Django 2.2.1 on 2019-05-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0006_businessapplication'),
        ('wholesale', '0008_auto_20190513_2041'),
    ]

    operations = [
    ]
