# Generated by Django 2.2 on 2019-05-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0009_merge_20190514_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AddField(
            model_name='customers',
            name='custLevel',
            field=models.IntegerField(default=1),
        ),
    ]
