# Generated by Django 2.2 on 2019-05-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0010_auto_20190514_1302'),
        ('wholesale', '0010_auto_20190514_0048'),
    ]

    operations = [
    ]
