# Generated by Django 2.1.8 on 2019-05-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0011_merge_20190514_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='disShipping',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='discount',
            name='maxQuan',
            field=models.IntegerField(default=2147483647),
        ),
        migrations.AlterField(
            model_name='products',
            name='max_quantity',
            field=models.IntegerField(default=2147483647),
        ),
    ]
