# Generated by Django 2.2 on 2019-05-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0012_auto_20190514_1420'),
        ('wholesale', '0011_merge_20190514_1427'),
    ]

    operations = [
    ]
