# Generated by Django 2.2 on 2019-05-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0013_merge_20190514_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
