# Generated by Django 2.2 on 2019-05-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0013_merge_20190529_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='disShipping',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.ManyToManyField(null=True, through='wholesale.Prod_dis', to='wholesale.Discount'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=50)),
                ('prodPrice', models.FloatField(default=0.0)),
                ('prodQuantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Customers')),
            ],
        ),
    ]
