# Generated by Django 2.2 on 2019-05-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0014_auto_20190528_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
    ]
