# Generated by Django 2.2 on 2019-05-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0014_auto_20190529_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prodPrice',
        ),
        migrations.AlterField(
            model_name='cart',
            name='prodName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Products'),
        ),
    ]
