# Generated by Django 2.2 on 2019-05-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0015_auto_20190528_1820'),
        ('wholesale', '0013_cart'),
    ]

    operations = [
    ]
